remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: FHE.org - A community of researchers interested in Fully Homomorphic Encryption
description: We are a community of researchers and developers interested in advancing homomorphic encryption and other secure computation techniques.
